### PR TITLE
Improve OpenAPI schema definitions for listings API

### PR DESCRIPTION
**Pull request by creichert**
**Improve OpenAPI schema definitions for listing API**

### CODE REVIEW

**Comment by creichert** [comment]
This is still waiting for support from Assertible for `nullable`

**Comment by CodyReichert** [comment]
Nice! I won't worry too much about updating the swagger spec right now - I want to move everything to the OAI3 document asap

**Comment by creichert** [comment]
Is it possible to move to it now, based on your comments in #11 there
had been some progress:

> Nice! I've actually been looking at updating to the new
> SwaggerUI. Everything seems to work just fine, so I think I can just
> swap it. I was hitting some errors on the latest swagger-ui version,
> but I'll look at it again.

Open a PR w/ the issue you hit please. Don't want to lose your work.

**Comment by CodyReichert** [comment]
https://github.com/SimplyRETS/docs.simplyrets.com/pull/15

There you go -- that does work, there's just a couple of minor CSS things to patch (because it's inheriting our theme _and_ the swagger-ui css).

---

I have another update to the spec I'll push that adds documentation/schemas for our `OPTIONS` requests.

**Pull request merged**
